#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d I II III IV V VI VII
#bspc monitor DP1 -d VIII IX X

bspc config top_padding         15
bspc config border_width        2
bspc config window_gap          12

bspc config automatic_scheme    spiral
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
#bspc config click_to_focus     true

### For bspwm colors ############
# . "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc rule -a Gimp state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a emacs state=tiled

#~/.config/scripts/lemonbar &
